
#include "hplmxp.hpp"

template <>
void HPLMXP_gemmNT(const int     m,
                   const int     n,
                   const int     k,
                   const double  alpha,
                   const double* a,
                   const int     lda,
                   const double* b,
                   const int     ldb,
                   const double  beta,
                   double*       c,
                   const int     ldc) {
  CUBLAS_CHECK(cublasGemmEx(blas_hdl,
                             CUBLAS_OP_N,
                             CUBLAS_OP_T,
                             m,
                             n,
                             k,
                             &alpha,
                             a,
                             CUDA_R_64F,
                             lda,
                             b,
                             CUDA_R_64F,
                             ldb,
                             &beta,
                             c,
                             CUDA_R_64F,
                             ldc,
                             CUBLAS_COMPUTE_64F,
                             CUBLAS_GEMM_DEFAULT));
}

template <>
void HPLMXP_gemmNT(const int    m,
                   const int    n,
                   const int    k,
                   const float  alpha,
                   const float* a,
                   const int    lda,
                   const float* b,
                   const int    ldb,
                   const float  beta,
                   float*       c,
                   const int    ldc) {
  CUBLAS_CHECK(cublasGemmEx(blas_hdl,
                             CUBLAS_OP_N,
                             CUBLAS_OP_T,
                             m,
                             n,
                             k,
                             &alpha,
                             a,
                             CUDA_R_32F,
                             lda,
                             b,
                             CUDA_R_32F,
                             ldb,
                             &beta,
                             c,
                             CUDA_R_32F,
                             ldc,
                             CUBLAS_COMPUTE_32F,
                             CUBLAS_GEMM_DEFAULT));
}

template <>
void HPLMXP_gemmNT(const int     m,
                   const int     n,
                   const int     k,
                   const float   alpha,
                   const __half* a,
                   const int     lda,
                   const __half* b,
                   const int     ldb,
                   const float   beta,
                   float*        c,
                   const int     ldc) {
  CUBLAS_CHECK(cublasGemmEx(blas_hdl,
                             CUBLAS_OP_N,
                             CUBLAS_OP_T,
                             m,
                             n,
                             k,
                             &alpha,
                             a,
                             CUDA_R_16F,
                             lda,
                             b,
                             CUDA_R_16F,
                             ldb,
                             &beta,
                             c,
                             CUDA_R_32F,
                             ldc,
                             CUBLAS_COMPUTE_32F,
                             CUBLAS_GEMM_DEFAULT));
}

template <>
void HPLMXP_gemmNT(const int     m,
                   const int     n,
                   const int     k,
                   const __half  alpha,
                   const __half* a,
                   const int     lda,
                   const __half* b,
                   const int     ldb,
                   const __half  beta,
                   __half*       c,
                   const int     ldc) {
  CUBLAS_CHECK(cublasGemmEx(blas_hdl,
                             CUBLAS_OP_N,
                             CUBLAS_OP_T,
                             m,
                             n,
                             k,
                             &alpha,
                             a,
                             CUDA_R_16F,
                             lda,
                             b,
                             CUDA_R_16F,
                             ldb,
                             &beta,
                             c,
                             CUDA_R_16F,
                             ldc,
                             CUBLAS_COMPUTE_32F,
                             CUBLAS_GEMM_DEFAULT));
}
